import 'package:discover_trips/models/trip.dart';

const List<Trip> tripsData = [
  Trip(
    id: 'm1',
    categories: [
      'c1',
    ],
    name: 'جبال الألب',
    tripType: TripType.adventure,
    season: Season.winter,
    imageUrl:
        'https://images.unsplash.com/photo-1611523658822-385aa008324c?ixid=MXwxMjA3fDB8MHxzZWFyY2h8N3x8bW91bmF0aW5zfGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    duration: 20,
    activities: [
      'التزلج على الجليد',
      'التنزه في المسارات الثلجية',
      'زيارة القرى الجبلية التاريخية',
      'التقاط الصور في المناطق الخلابة',
      'تناول وجبات تقليدية في الأكواخ الجبلية',
    ],
    program: [
      'اليوم الأول: الوصول إلى القرية الجبلية والترحيب بالزوار.',
      'اليوم الثاني: جولة استكشافية في الغابات المغطاة بالثلوج.',
      'اليوم الثالث: تجربة التزلج على الجليد مع دليل محترف.',
      'اليوم الرابع: زيارة المتاحف المحلية والأسواق التقليدية.',
      'اليوم الخامس: رحلة إلى أعلى القمم مع الاستمتاع بمناظر بانورامية.',
      'اليوم السادس: يوم حر للاستمتاع بالأنشطة الفردية.',
      'اليوم الأخير: التوديع والمغادرة إلى الوجهة التالية.',
    ],
    isInSummer: false,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm2',
    categories: [
      'c1',
    ],
    name: 'جبال الجنوب',
    tripType: TripType.adventure,
    season: Season.winter,
    imageUrl:
        'https://images.unsplash.com/photo-1612456225451-bb8d10d0131d?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjZ8fG1vdW5hdGluc3xlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    duration: 10,
    activities: [
      'التخييم في الطبيعة الجبلية',
      'رحلة استكشافية وسط الغابات المحيطة',
      'تسلق المرتفعات الجبلية',
      'التقاط الصور في أماكن طبيعية مذهلة',
      'تناول عشاء مشوي في أجواء مفتوحة',
    ],
    program: [
      'اليوم الأول: الوصول إلى المخيم وتحديد موقع التخييم.',
      'اليوم الثاني: القيام بجولة استكشافية قصيرة حول المنطقة.',
      'اليوم الثالث: تسلق الجبل الرئيسي في المنطقة.',
      'اليوم الرابع: استكشاف الكهوف القريبة والتعرف على تاريخها.',
      'اليوم الخامس: قضاء وقت حر للتصوير والاستمتاع بالطبيعة.',
      'اليوم السادس: تنظيم حفلة شواء جماعية مع باقي الزوار.',
      'اليوم السابع: العودة إلى المدينة بعد تناول وجبة الإفطار.',
    ],
    isInSummer: false,
    isForFamilies: false,
    isInWinter: true,
  ),
  Trip(
    id: 'm3',
    categories: [
      'c1',
    ],
    name: 'جبال مرتفعة',
    tripType: TripType.recovery,
    season: Season.winter,
    imageUrl:
        'https://images.unsplash.com/photo-1592221912790-2b4df8882ea9?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mzd8fG1vdW5hdGluc3xlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    duration: 45,
    activities: [
      'التنزه على قمم الجبال',
      'جلسات استجمام في الطبيعة',
      'التقاط الصور التذكارية',
      'التأمل والاسترخاء بجانب الشلالات',
      'تناول وجبات صحية في الهواء الطلق',
    ],
    program: [
      'اليوم الأول: الوصول إلى المنتجع والتعرف على المرافق.',
      'اليوم الثاني: جولة تنزه قصيرة لاكتشاف المناطق المحيطة.',
      'اليوم الثالث: جلسات استرخاء وتأمل بجانب الشلال.',
      'اليوم الرابع: الاستمتاع بجلسة علاج طبيعي في الطبيعة.',
      'اليوم الخامس: تنظيم رحلة استكشافية إلى قمم الجبال.',
      'اليوم السادس: قضاء وقت حر للتصوير والاسترخاء.',
      'اليوم السابع: العودة إلى المنتجع وتوديع الطبيعة.',
    ],
    isInSummer: false,
    isForFamilies: false,
    isInWinter: true,
  ),
  Trip(
    id: 'm4',
    categories: [
      'c2',
    ],
    name: 'البحيرة الكبرى',
    tripType: TripType.recovery,
    season: Season.spring,
    imageUrl:
        'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixid=MXwxMjA3fDB8MHxzZWFyY2h8OXx8bGFrZXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    duration: 60,
    activities: [
      'التمتع بالمشي حول البحيرة',
      'ركوب القوارب في البحيرة',
      'زيارة الجزر الصغيرة القريبة',
      'التقاط الصور من أعلى الجسر',
      'التجول في المناطق المحيطة بالبحيرة'
    ],
    program: [
      'اليوم الأول: الوصول إلى البحيرة والاستمتاع بالمشي حولها.',
      'اليوم الثاني: ركوب القوارب واستكشاف الجزر الصغيرة.',
      'اليوم الثالث: زيارة المناطق المحيطة بالبحيرة والتقاط الصور.',
      'اليوم الرابع: الاستمتاع بمغامرة المشي في الطبيعة.',
      'اليوم الخامس: وقت حر للاسترخاء بجانب البحيرة.',
      'اليوم السادس: العودة إلى المدينة والقيام بجولة تسويقية.',
    ],
    isInSummer: false,
    isForFamilies: false,
    isInWinter: false,
  ),
  Trip(
    id: 'm5',
    categories: [
      'c2',
    ],
    name: 'البحيرات الصغرى',
    tripType: TripType.activities,
    season: Season.winter,
    imageUrl:
        'https://images.unsplash.com/photo-1580100586938-02822d99c4a8?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjF8fGxha2V8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
    duration: 15,
    activities: [
      'التزلج على البحيرات المتجمدة',
      'جولة سياحية على الأقدام في المناطق المحيطة',
      'استكشاف الحياة البرية الشتوية',
      'التقاط صور طبيعية رائعة',
      'تناول مشروبات دافئة بالقرب من البحيرة'
    ],
    program: [
      'اليوم الأول: الوصول إلى البحيرات المتجمدة والتمتع بالتزلج عليها.',
      'اليوم الثاني: جولة سياحية على الأقدام في المناطق المحيطة بالبحيرة.',
      'اليوم الثالث: استكشاف الحياة البرية الشتوية والتقاط الصور.',
      'اليوم الرابع: زيارة المراكز التجارية للتسوق.',
      'اليوم الخامس: الاسترخاء والاستمتاع بالمشروبات الدافئة بالقرب من البحيرة.',
      'اليوم السادس: العودة إلى المدينة بعد قضاء وقت ممتع.'
    ],
    isInSummer: false,
    isForFamilies: false,
    isInWinter: true,
  ),
  Trip(
    id: 'm6',
    categories: [
      'c2', // قد تكون فئة طبيعية أو جبلية
    ],
    name: 'بحيرة الزمرد',
    tripType: TripType.romantic,
    season: Season.summer,
    imageUrl:
        'https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8bGFrZXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
    duration: 240, // مدة الرحلة لمدة يوم كامل
    activities: [
      'الاستمتاع بالمشي بجانب البحيرة',
      'التجديف بالقوارب الصغيرة',
      'زيارة المواقع الأثرية المحيطة',
      'الاسترخاء في الأماكن المخصصة بالقرب من البحيرة',
      'التقاط صور المناظر الطبيعية'
    ],
    program: [
      'اليوم الأول: الوصول إلى بحيرة الزمرد والتمتع بالمشي بجانب المياه.',
      'اليوم الثاني: القيام بجولة بالقوارب الصغيرة للاستمتاع بالمناظر الطبيعية الخلابة.',
      'اليوم الثالث: زيارة المواقع الأثرية المحيطة والتعرف على تاريخ المنطقة.',
      'اليوم الرابع: الاسترخاء في المناطق المخصصة بالقرب من البحيرة.',
      'اليوم الخامس: التقاط صور للمناظر الطبيعية الرائعة وقضاء الوقت في التنزه.',
      'اليوم السادس: العودة إلى المدينة بعد الاستمتاع بيوم من الهدوء.'
    ],
    isInSummer: true,
    isForFamilies: false,
    isInWinter: false,
  ),
  Trip(
    id: 'm7',
    categories: [
      'c3',
      'c2',
    ],
    name: 'شاطئ ',
    tripType: TripType.adventure,
    season: Season.winter,
    imageUrl:
        'https://images.unsplash.com/photo-1493558103817-58b2924bce98?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTAxfHxiZWFjaHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
    duration: 20,
    activities: [
      'زيارة المواقع الأثرية',
      'جولة سياحية على الأقدام',
      'زيارة المراكز التجارية للتبضع',
      'تناول وجبة الغداء',
      'استمتاع المناظر الجملية',
      'التمتع بالرياضات المائية مثل ركوب الأمواج أو السباحة'
    ],
    program: [
      'اليوم الأول: الوصول إلى الشاطئ والاستمتاع بالمشي على الرمال.',
      'اليوم الثاني: تجربة الأنشطة المائية مثل السباحة وركوب الأمواج.',
      'اليوم الثالث: زيارة المعالم السياحية المجاورة والتعرف على تاريخ المنطقة.',
      'اليوم الرابع: الاسترخاء على الشاطئ والتمتع بالمناظر الجمالية.',
    ],
    isInSummer: true,
    isForFamilies: false,
    isInWinter: false,
  ),
  Trip(
    id: 'm8',
    categories: [
      'c3',
    ],
    name: 'الشاطئ الكبير',
    tripType: TripType.recovery,
    season: Season.spring,
    imageUrl:
        'https://images.unsplash.com/photo-1519046904884-53103b34b206?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mnx8YmVhY2h8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    duration: 35,
    activities: [
      'زيارة المواقع الأثرية',
      'جولة سياحية على الأقدام',
      'زيارة المراكز التجارية للتبضع',
      'تناول وجبة الغداء',
      'استمتاع المناظر الجملية',
    ],
    program: [
      'اليوم الأول: الوصول إلى الشاطئ والاسترخاء على الرمال.',
      'اليوم الثاني: استمتاع بأوقات هادئة على الشاطئ.',
      'اليوم الثالث: زيارة المعالم السياحية والتعرف على التاريخ المحلي.',
      'اليوم الرابع: الاسترخاء والتمتع بالمشاهد الطبيعية الخلابة.',
    ],
    isInSummer: true,
    isForFamilies: false,
    isInWinter: true,
  ),
  Trip(
    id: 'm9',
    categories: [
      'c3',
    ],
    name: 'شاطئ الصخور',
    tripType: TripType.activities,
    season: Season.summer,
    imageUrl:
        'https://images.unsplash.com/photo-1519602035691-16ac091344ef?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjE1fHxiZWFjaHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
    duration: 45,
    activities: [
      'زيارة المواقع الأثرية',
      'جولة سياحية على الأقدام',
      'زيارة المراكز التجارية للتبضع',
      'تناول وجبة الغداء',
      'استمتاع المناظر الجملية',
    ],
    program: [
      'اليوم الأول: الوصول إلى الشاطئ والاستمتاع بالموقع.',
      'اليوم الثاني: استكشاف الشاطئ وزيارة المواقع الأثرية.',
      'اليوم الثالث: جولة سياحية والاستمتاع بالغروب على الشاطئ.',
      'اليوم الرابع: استرخاء على الرمال مع تناول وجبة الغداء.',
    ],
    isInSummer: true,
    isForFamilies: false,
    isInWinter: false,
  ),
  Trip(
    id: 'm10',
    categories: ['c3'],
    name: 'شاطىء الرمال',
    imageUrl:
        'https://images.unsplash.com/photo-1725723959323-0c5119e13651?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fCVEOCVCNCVEOCVBNyVEOCVCNyVEOSU4OSVEOCVBMSUyMCVEOCVCOSVEOCVBQyVEOSU4QSVEOCVBOCVEOCVBOSVEOCU4QyUyMG1lcnNhJTIwbWF0cnVofGVufDB8fDB8fHww',
    activities: [
      'السباحة',
      'التزلج على الأمواج',
      'التنزه على الشاطىء',
      'تناول وجبة بحرية',
    ],
    program: [
      'اليوم الأول: الاسترخاء على الشاطىء',
      'اليوم الثاني: جولة بحرية بالقارب',
      'اليوم الثالث: زيارة المعالم السياحية',
      'اليوم الرابع: وقت حر للاستمتاع',
      'اليوم الخامس: تناول وجبة بحرية',
    ],
    duration: 45,
    season: Season.summer,
    tripType: TripType.adventure,
    isInSummer: true,
    isInWinter: false,
    isForFamilies: false,
  ),
  Trip(
    id: 'm11',
    categories: ['c6'],
    name: 'حديقة الألعاب',
    imageUrl:
        'https://plus.unsplash.com/premium_photo-1721265240898-58ec9f4e2aa2?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fFBsYXlncm91bmR8ZW58MHx8MHx8fDA%3D',
    activities: [
      'التنزه في الحديقة',
      'الاستمتاع بالألعاب الترفيهية',
      'الاستراحة في المقاهي',
    ],
    program: [
      'اليوم الأول: زيارة المعالم في الحديقة',
      'اليوم الثاني: الاستمتاع بالألعاب الترفيهية',
      'اليوم الثالث: المشاركة في الأنشطة الترفيهية',
      'اليوم الرابع: استراحة في المقاهي',
      'اليوم الخامس: زيارة الأسواق التقليدية',
    ],
    duration: 30,
    season: Season.spring,
    tripType: TripType.family,
    isInSummer: false,
    isInWinter: false,
    isForFamilies: true,
  ),
  Trip(
    id: 'm12',
    categories: ['c1'],
    name: 'الجبال الشاهقة',
    imageUrl:
        'https://images.unsplash.com/photo-1717711081295-26716146b205?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGhpZ2glMjBtb3VudGFpbnN8ZW58MHx8MHx8fDA%3D',
    activities: [
      'التسلق الجبلي',
      'التخييم',
      'رحلات مشي لمسافات طويلة',
    ],
    program: [
      'اليوم الأول: الوصول والتجهيز للتسلق',
      'اليوم الثاني: التسلق الجبلي',
      'اليوم الثالث: التخييم في الطبيعة',
      'اليوم الرابع: مغامرة مشي لمسافات طويلة',
      'اليوم الخامس: رحلة العودة',
    ],
    duration: 60,
    season: Season.summer,
    tripType: TripType.adventure,
    isInSummer: true,
    isInWinter: false,
    isForFamilies: false,
  ),
  Trip(
    id: 'm13',
    categories: [
      'c4',
    ],
    name: 'الصحراء الكبرى',
    tripType: TripType.activities,
    season: Season.winter,
    imageUrl:
        'https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8ZGVzZXJ0fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    duration: 30,
    activities: [
      'زيارة المواقع الأثرية',
      'جولة سياحية على الأقدام',
      'زيارة المراكز التجارية للتبضع',
      'تناول وجبة الغداء',
      'الاستمتاع بالمناظر الجميلة',
    ],
    program: [
      'اليوم الأول: الوصول إلى الصحراء وجولة تعريفية.',
      'اليوم الثاني: زيارة المواقع الأثرية القديمة.',
      'اليوم الثالث: جولة سياحية على الأقدام والتخييم.',
      'اليوم الرابع: تناول وجبة الغداء وسط الطبيعة.',
      'اليوم الخامس: رحلة إلى الواحات المجاورة.',
      'اليوم السادس: الاستمتاع بالمناظر الطبيعية والمغادرة.',
    ],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm14',
    categories: ['c5'],
    name: 'المدينة القديمة',
    imageUrl:
        'https://images.unsplash.com/photo-1517491093410-ab48c47bc750?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8b2xkJTIwY2l0eXN8ZW58MHx8MHx8fDA%3D',
    activities: [
      'زيارة المواقع الأثرية',
      'جولة سياحية في المدينة القديمة',
      'زيارة المتاحف',
    ],
    program: [
      'اليوم الأول: جولة في المعالم التاريخية',
      'اليوم الثاني: زيارة الأسواق التقليدية',
      'اليوم الثالث: زيارة المتاحف والفن',
      'اليوم الرابع: الاستمتاع بالفن والموسيقى التقليدية',
      'اليوم الخامس: يوم حر للاستكشاف',
    ],
    duration: 40,
    season: Season.spring,
    tripType: TripType.cultural,
    isInSummer: false,
    isInWinter: false,
    isForFamilies: true,
  ),
  Trip(
    id: 'm15',
    categories: ['c6'],
    name: 'رياضة التثلج',
    imageUrl:
        'https://images.unsplash.com/photo-1605540436563-5bca919ae766?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8c2tpaW5nfGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
    activities: [
      'التزلج على الجليد',
      'التزحلق على الجليد',
      'رحلات سفاري الثلوج',
    ],
    program: [
      'اليوم الأول: الوصول والتجهيز للتزلج',
      'اليوم الثاني: التزلج على المنحدرات',
      'اليوم الثالث: جولة سفاري ثلجية',
      'اليوم الرابع: التزلج في المناطق الوعرة',
      'اليوم الخامس: استكشاف المناظر الطبيعية الثلجية',
    ],
    duration: 30,
    season: Season.winter,
    tripType: TripType.adventure,
    isInSummer: false,
    isInWinter: true,
    isForFamilies: true,
  ),
  Trip(
    id: 'm16',
    categories: ['c4'],
    name: 'جولة السفاري في الصحراء',
    imageUrl:
        'https://images.unsplash.com/photo-1452022582947-b521d8779ab6?ixid=MXwxMjA3fDB8MHxzZWFyY2h8ODN8fGRlc2VydHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
    activities: [
      'جولة سفاري بالصحراء',
      'زيارة معسكرات بدوية',
      'رحلة على الجمال',
    ],
    program: [
      'اليوم الأول: الوصول والتخييم في الصحراء',
      'اليوم الثاني: جولة سفاري بالصحراء',
      'اليوم الثالث: زيارة المعسكرات البدوية',
      'اليوم الرابع: رحلة على الجمال',
      'اليوم الخامس: الاستمتاع بالمناظر الطبيعية والعودة',
    ],
    duration: 60,
    season: Season.winter,
    tripType: TripType.adventure,
    isInSummer: false,
    isInWinter: true,
    isForFamilies: false,
  ),
  Trip(
    id: '17',
    categories: ['c5'],
    name: 'استكشاف المدينة القديمة',
    imageUrl:
        'https://images.unsplash.com/photo-1574513828579-0c1b434d66df?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    activities: [
      'زيارة المعالم الأثرية',
      'جولة سياحية في الأسواق التقليدية',
      'زيارة المتاحف',
      'التجول في الأحياء القديمة',
    ],
    program: [
      'اليوم الأول: الوصول وزيارة المعالم الأثرية',
      'اليوم الثاني: جولة في الأسواق التقليدية',
      'اليوم الثالث: زيارة المتاحف',
      'اليوم الرابع: التجول في الأحياء القديمة',
      'اليوم الخامس: الاستمتاع بالفن التقليدي والعروض',
    ],
    duration: 5,
    season: Season.spring,
    tripType: TripType.cultural,
    isInSummer: false,
    isInWinter: false,
    isForFamilies: false,
  ),
  Trip(
    id: 'm18',
    categories: [
      'c5',
    ],
    name: 'المدينة ',
    tripType: TripType.activities,
    season: Season.winter,
    imageUrl:
        'https://images.unsplash.com/photo-1498307833015-e7b400441eb8?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NDJ8fHRyYXZlbHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
    duration: 30,
    activities: [
      'زيارة المواقع الأثرية',
      'جولة سياحية على الأقدام',
      'زيارة المراكز التجارية للتبضع',
      'تناول وجبة الغداء',
      'الاستمتاع بالمناظر الجميلة',
    ],
    program: [
      'اليوم الأول: الوصول وزيارة المواقع الأثرية.',
      'اليوم الثاني: جولة سياحية على الأقدام في المناطق التاريخية.',
      'اليوم الثالث: زيارة المراكز التجارية للتبضع.',
      'اليوم الرابع: تناول وجبة الغداء في المطاعم المحلية.',
      'اليوم الخامس: الاستمتاع بالمناظر الطبيعية والمغادرة.',
    ],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm19',
    categories: [
      'c4',
    ],
    name: 'الصحراء الغربية',
    tripType: TripType.activities,
    season: Season.winter,
    imageUrl:
        'https://plus.unsplash.com/premium_photo-1661962697678-9bf7f75eb561?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8U2FoYXJhJTIwZGVzZXJ0fGVufDB8fDB8fHww',
    duration: 30,
    activities: [
      'زيارة المواقع الأثرية',
      'جولة سياحية على الأقدام',
      'زيارة الأسواق التقليدية',
      'تناول وجبة الغداء',
      'الاستمتاع بالمناظر الطبيعية',
    ],
    program: [
      'اليوم الأول: الوصول إلى الصحراء واستكشاف الموقع.',
      'اليوم الثاني: زيارة المواقع الأثرية الشهيرة.',
      'اليوم الثالث: جولة على الأقدام في المناطق السياحية.',
      'اليوم الرابع: التسوق في الأسواق التقليدية.',
      'اليوم الخامس: استكشاف الواحات القريبة وتناول الغداء.',
      'اليوم السادس: التقاط الصور التذكارية والاستمتاع بالطبيعة قبل المغادرة.',
    ],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: true,
  ),
];
